{{- $nameSpace := include "appsmith.namespace" . -}}
{{- $mongoUser := .Values.mongodb.auth.rootUser -}}
{{- $mongoPassword := .Values.mongodb.auth.rootPassword -}}
{{- $mongoServicename := .Values.mongodb.service.nameOverride -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appsmith.fullname" . }}
  namespace: {{ include "appsmith.namespace" . }}
  labels:
    {{- include "appsmith.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.applicationConfig }}
  {{- if and (eq "APPSMITH_MONGODB_URI" $key) ( not $value) }}
  {{ $key }}: mongodb+srv://{{ $mongoUser }}:{{ $mongoPassword }}@{{ $mongoServicename }}.{{ $nameSpace }}.svc.cluster.local/appsmith?retryWrites=true&authSource=admin&ssl=false
  {{- end }}
  {{- if and (eq "APPSMITH_REDIS_URL" $key) ( not $value) }}
  {{ $key }}: redis://appsmith-redis-master.{{ $nameSpace }}.svc.cluster.local:6379
  {{- end }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
